permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

title: "甜小立"
description: "甜小立的网络小空间"
keywords: ""
url: https://solome.js.org
baseurl: "/thf"

repo: http://github.com/solome/thf

author:
  name      : "甜小立"
  job       : "工程师"
  bio       : "給國防領域“拖後腿”的工程師..."
  thumb     : /images/thf.png
  email     : annethf@outlook.com
  url       : https://solome.js.org/thf
  github    : https://github.com/annethf

navbar:
  - slug: about
    title: about
  - slug: blog
    title: blog
  - slug: resume
    title: resume

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
